openapi: 3.0.0
info:
  title: Notes API
  version: 1.0.0
  description: 노트 관리 API

paths:
  /notes:
    post:
      summary: 노트 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tag:
                  type: string
              required:
                - title
                - content
      responses:
        '201':
          description: 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Note'
    get:
      summary: 전체 노트 조회
      responses:
        '201':
          description: 전체 노트 목록 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Note'

  /notes/{tag}:
    get:
      summary: 태그별 노트 조회
      parameters:
        - in: path
          name: tag
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 태그별 노트 목록 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Note'

  /notes/{id}:
    put:
      summary: 노트 수정
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tag:
                  type: string
      responses:
        '200':
          description: 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Note'
        '404':
          description: 노트 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: 노트 삭제
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 삭제 성공
        '404':
          description: 노트 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        tag:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time